### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by eltiare** [mdirolf/nginx-gridfs#13]
I've been trying to get this to work for a while now and can't get it to work. I've checked the nginx error logs and nothing is ever outputted there. The server just returns a 404 error. Here is my config:

<pre>
server {
   listen 80;
   server_name hostname.com;
   location /gridfs {
     gridfs db_name root_collection=fs.files field=filename type=string;
     mongo 127.0.0.1:27017;
   }
}
</pre>

I'm using the Mongoid ORM with Carrierwave. When accessing the database directly, I notice that there are two collections: "fs.files" and "fs.chunks". Am I supposed to reference the "fs.chunks" collection instead? This works in the Rails console:

<pre>
db = Mongoid.database
col = db.collection('fs.files')
col.find_one('filename' => 'image/web/4c4e247e0190bd235e000006/untitled-5557.jpg')
 => {"_id"=>BSON::ObjectID('4c4e24870190bd235e000007'), "filename"=>"image/web/4c4e247e0190bd235e000006/untitled-5557.jpg", "contentType"=>"application/octet-stream", "length"=>1898696, "chunkSize"=>262144, "uploadDate"=>2010-07-27 00:12:56 UTC, "md5"=>"ba2121656dceddb47f9e42415624e25f"} 
</pre>

But when I try:

http://hostname.com/gridfs/image/web/4c4e247e0190bd235e000006/untitled-5557.jpg

I get a 404. Any direction here would be appreciated.

**Comment by ctriolo** [comment]
_root_collection_ is equivalent to the _prefix_ used by a GridFS. Looks like in this case you are using GridFS's default prefix which is **fs**. To fix this issue either set `root_collection=fs` or simply remove that parameter as nginx-gridfs defaults to it. I'll update the README to make this more clear.
For additional info on how GridFS works take a look at the [specification](http://www.mongodb.org/display/DOCS/GridFS+Specification).

**Comment by eltiare** [comment]
Thank you so much for your help. Looks like it is working great now!

**Comment by mdirolf** [comment]
glad you got this working - closing this issue
