### ISSUE TITLE
Error compiling module with mongo-c-driver

### ISSUE THREAD

**Issue by Kronuz** [mdirolf/nginx-gridfs#19]
Compiling nginx, I'm getting this error:
    gcc -c -O -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Wunused-function -Wunused-variable -Wunused-value -Werror -g -O3 -D_LARGEFILE_SOURCE -DBUILDING_NGINX --std=c99 -Isrc  -I src/core -I src/event -I src/event/modules -I src/os/unix -I ../nginx_http_push_module/src -I objs -I src/http -I src/http/modules -I src/mail \
                    -o objs/addon/src/_.o \
                    ../nginx_gridfs/mongo-c-driver/src/_.c
    i686-apple-darwin10-gcc-4.2.1: cannot specify -o with -c or -S with multiple files
    make[1]: **\* [objs/addon/src/ngx_http_headers_more_filter_module.o] Error 1
    make: **\* [build] Error 2

and I fixed it by specifying the files one by one instead of using '*', in config:
    ngx_addon_name=ngx_http_gridfs_module
    HTTP_MODULES="$HTTP_MODULES ngx_http_gridfs_module"
    NGX_ADDON_SRCS="$NGX_ADDON_SRCS $ngx_addon_dir/ngx_http_gridfs_module.c $ngx_addon_dir/mongo-c-driver/src/bson.c $ngx_addon_dir/mongo-c-driver/src/gridfs.c $ngx_addon_dir/mongo-c-driver/src/md5.c $ngx_addon_dir/mongo-c-driver/src/mongo.c $ngx_addon_dir/mongo-c-driver/src/numbers.c"
    NGX_ADDON_DEPS="$NGX_ADDON_DEPS $ngx_addon_dir/mongo-c-driver/src/bson.h $ngx_addon_dir/mongo-c-driver/src/gridfs.h $ngx_addon_dir/mongo-c-driver/src/md5.h $ngx_addon_dir/mongo-c-driver/src/mongo_except.h $ngx_addon_dir/mongo-c-driver/src/mongo.h $ngx_addon_dir/mongo-c-driver/src/platform_hacks.h"
    CFLAGS="$CFLAGS --std=c99 -Isrc"

**Comment by mdirolf** [comment]
feel like submitting a pull request for this? would be happy to merge it in

**Comment by Kronuz** [comment]
Don't have a clone of your repo :(
...but it's a very straightforward and simple change ...just those few lines, and I think it's worth it :)

And hey! Thanks for nginx-gridfs! :D
