### ISSUE TITLE
Can't build on OSX 10.6

### ISSUE THREAD

**Issue by ghost** [mdirolf/nginx-gridfs#2]
I haven't tried to build on 10.5 but it seems to be failing for me on 10.6. Configures OK then fails with:

Undefined symbols:
  "boost::system::get_system_category()", referenced from:
      __static_initialization_and_destruction_0(int, int)in gridfs_c_helpers.o
      __static_initialization_and_destruction_0(int, int)in gridfs_c_helpers. (snip)

I used macports to install boost + other deps, 32 bit I believe. Error is the same trying against 32 and 64 bit MongoDB.

Can provide more information if required. thanks!

**Comment by sho** [comment]
This issue is solved; you can close it!

**Comment by mdirolf** [comment]
Thanks Sho!
