### ISSUE TITLE
Regex and or partial url match?

### ISSUE THREAD

**Issue by hlidotbe** [mdirolf/nginx-gridfs#22]
Hi,

nginx-grifs work very well but for my projects I need the urls to have non-identifying info (read SEO garbage). Unfortunately it's not possible to have this stuff in the "physical" filename (translations, frequent changes, ...).

So the question is: how complex would it be to have nginx-grifs use a variable instead of the rest of the url for filename matching? Like fastcgi_param does for processing files.

Thanks,
Hugues

**Comment by mdirolf** [comment]
you mean use a query param? shouldn't be too hard but i honestly just don't have the time now. if you feel like giving it a shot i'd be happy to merge!

**Comment by hlidotbe** [comment]
Ouch :) I don't think my c skills are up to the task but I'll try to work something out

**Comment by hlidotbe** [comment]
ok, no need to flex my long lost c skills, a simple rewrite work perfectly!
Combined with a bit of error_page trickery I get the perfect setup.

**Comment by mdirolf** [comment]
great, glad it's working out for you!
