### ISSUE TITLE
corrupting first 8 bytes

### ISSUE THREAD

**Issue by ghost** [mdirolf/nginx-gridfs#3]
I can't identify a cause, but the module often corrupts the first 8 bytes of all files it serves. Appears to happen on linux but not on OSX. Troubleshooting hints welcome ...

**Comment by sho** [comment]
Here's the issue "in action". Context is an image server.

ruby side:

> > files.find_one "filename" => '4aa814a2321c6069ba00404b_240.jpg'
> > => {"_id"=>4aa86da3321c60692600b97f, "filename"=>"4aa814a2321c6069ba00404b_240.jpg", "contentType"=>"image/jpeg", "length"=>22302, "chunkSize"=>262144, "uploadDate"=>Thu Sep 10 03:08:19 UTC 2009, "aliases"=>nil, "metadata"=>{"height"=>180, "width"=>240}, "md5"=>"6d744beca173cca4050f91ca95a388c4"}

get it from the nginx module:

$ wget http://10.1.1.18/img/4aa814a2321c6069ba00404b_240.jpg
--2009-10-11 11:56:22--  http://10.1.1.18/img/4aa814a2321c6069ba00404b_240.jpg
Connecting to 10.1.1.18:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 22302 (22K) [text/plain]
Saving to: `4aa814a2321c6069ba00404b_240.jpg'

100%[======================================>] 22,302      34.2K/s   in 0.6s    

2009-10-11 11:56:23 (34.2 KB/s) - `4aa814a2321c6069ba00404b_240.jpg' saved [22302/22302]

through a Ruby pass-through:

$ wget http://10.1.1.18/images/show/4aa814a2321c6069ba00404b_240.jpg
--2009-10-11 11:56:39--  http://10.1.1.18/images/show/4aa814a2321c6069ba00404b_240.jpg
Connecting to 10.1.1.18:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 22302 (22K) [image/jpeg]
Saving to: `4aa814a2321c6069ba00404b_240.jpg.1'

100%[======================================>] 22,302      40.7K/s   in 0.5s    

2009-10-11 11:56:40 (40.7 KB/s) - `4aa814a2321c6069ba00404b_240.jpg.1' saved [22302/22302]

$ md5 4aa814a2321c6069ba00404b_240.jpg
MD5 (4aa814a2321c6069ba00404b_240.jpg) = 1a57487dc3833e3adeec626181774b20
$ md5 4aa814a2321c6069ba00404b_240.jpg.1 
MD5 (4aa814a2321c6069ba00404b_240.jpg.1) = 6d744beca173cca4050f91ca95a388c4
$ cmp -l 4aa814a2321c6069ba00404b_240.jpg 4aa814a2321c6069ba00404b_240.jpg.1 
    1   0 377
    2   0 330
    3   0 377
    4   0 340
    6   0  20
    7   0 112
    8   0 106

Length is correct but the first 8 bytes are zeroed. Perhaps of interest is that I am not seeing this issue on OSX, only on Linux.

**Comment by mdirolf** [comment]
hmm thanks for the detailed output. will try to take a look at this as soon as i get a chance

**Comment by sho** [comment]
I hate to be a pain but is a fix to this likely anytime soon? If not, I will have to change my plans a bit.

**Comment by mdirolf** [comment]
I'll try to take a look at it as soon as I can. Sorry this project has been sort of slow moving I just have a lot on my plate right now - would be glad to accept patches!

**Comment by jszmajda** [comment]
fwiw this doesn't happen to me on Ubuntu 9.10 with nginx 0.8.30 and nginx-gridfs rev 0d6a759b72fdf167cd75d1f23339139ed76a6c2f

**Comment by mdirolf** [comment]
Thanks for the feedback, Josh. Yeah it seems really strange that that would happen, not sure how it's happening. Haven't had too much of a chance to dig in yet, though

**Comment by sho** [comment]
Hm, I tried with nginx 0.8.30 & latest master and the problem still exists. This is on RHEL5. Again, first 8 bytes are zeroes. Works beautifully on OSX.

I have no idea what the problem could be, don't even know where to start. Sorry for not being able to help. Maybe I should just change to ubuntu as well!

**Comment by sho** [comment]
Hm. I merged stunti's changes, along with joshsz's, and it seems to have fixed the issue. 

Specifically this commit: http://github.com/stunti/nginx-gridfs/commit/15eebd1cf54aded8403d02f3e5a97fa578ecc55a

I will continue testing but initial results look good ... : )

**Comment by mdirolf** [comment]
I've applied those changes to master
