### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by xonze** [mdirolf/nginx-gridfs#31]
Linux vm.centos.64 2.6.18-238.el5 #1 SMP Thu Jan 13 15:51:15 EST 2011 x86_64 x86_64 x86_64 GNU/Linux

nginx 1.0.4

[root@vm nginx-1.0.4]# ./configure --user=www --group=www --prefix=/usr/local/nginx --with-http_stub_status_module --with-http_ssl_module --with-http_gzip_static_module --with-ipv6 --add-module=/root/mdirolf-nginx-gridfs-v0.8

[root@vm nginx-1.0.4]# make
==================error tips========================================
 -o objs/addon/mdirolf-nginx-gridfs-v0.8/ngx_http_gridfs_module.o \
                ../../mdirolf-nginx-gridfs-v0.8//ngx_http_gridfs_module.c
../../mdirolf-nginx-gridfs-v0.8/ngx_http_gridfs_module.c: In function ‘ngx_http_mongo_reconnect’:
../../mdirolf-nginx-gridfs-v0.8/ngx_http_gridfs_module.c:570: warning：隐式声明函数 ‘MONGO_TRY_GENERIC’
../../mdirolf-nginx-gridfs-v0.8/ngx_http_gridfs_module.c:570: error：expected ‘;’ before ‘{’ token
../../mdirolf-nginx-gridfs-v0.8/ngx_http_gridfs_module.c: In function ‘ngx_http_mongo_reauth’:
../../mdirolf-nginx-gridfs-v0.8/ngx_http_gridfs_module.c:614: error：expected ‘;’ before ‘{’ token
../../mdirolf-nginx-gridfs-v0.8/ngx_http_gridfs_module.c: In function ‘ngx_http_gridfs_handler’:
../../mdirolf-nginx-gridfs-v0.8/ngx_http_gridfs_module.c:755: error：expected ‘;’ before ‘{’ token
../../mdirolf-nginx-gridfs-v0.8/ngx_http_gridfs_module.c:790: error：expected ‘;’ before ‘{’ token
../../mdirolf-nginx-gridfs-v0.8/ngx_http_gridfs_module.c:898: error：expected ‘;’ before ‘{’ token
make[1]: **\* [objs/addon/mdirolf-nginx-gridfs-v0.8/ngx_http_gridfs_module.o] error 1
make[1]: Leaving directory `/root/lnmp0.7-full/nginx-1.0.4
make: **\* [build] error 2
===================error tips end===================================

**Comment by xonze** [comment]
nginx 0.8.54

/root/mdirolf-nginx-gridfs-v0.8/ngx_http_gridfs_module.c: In function ‘ngx_http_mongo_reconnect’:
/root/mdirolf-nginx-gridfs-v0.8/ngx_http_gridfs_module.c:570: warning：隐式声明函数 ‘MONGO_TRY_GENERIC’
/root/mdirolf-nginx-gridfs-v0.8/ngx_http_gridfs_module.c:570: error：expected ‘;’ before ‘{’ token
/root/mdirolf-nginx-gridfs-v0.8/ngx_http_gridfs_module.c: In function ‘ngx_http_mongo_reauth’:
/root/mdirolf-nginx-gridfs-v0.8/ngx_http_gridfs_module.c:614: error：expected ‘;’ before ‘{’ token
/root/mdirolf-nginx-gridfs-v0.8/ngx_http_gridfs_module.c: In function ‘ngx_http_gridfs_handler’:
/root/mdirolf-nginx-gridfs-v0.8/ngx_http_gridfs_module.c:755: error：expected ‘;’ before ‘{’ token
/root/mdirolf-nginx-gridfs-v0.8/ngx_http_gridfs_module.c:790: error：expected ‘;’ before ‘{’ token
/root/mdirolf-nginx-gridfs-v0.8/ngx_http_gridfs_module.c:898: error：expected ‘;’ before ‘{’ token
make[1]: **\* [objs/addon/mdirolf-nginx-gridfs-v0.8/ngx_http_gridfs_module.o] error 1
make[1]: Leaving directory `/root/lnmp0.7-full/nginx-0.8.54'

**Comment by macroon** [comment]
#include "mongo-c-driver/src/mongo.h"
#include "mongo-c-driver/src/bson.h"
#include "mongo-c-driver/src/gridfs.h"

我增加了#include "mongo-c-driver/src/bson.h"这个后可以编译通过！

**Comment by xonze** [comment]
谢谢！
这个问题挺奇怪的，后来我用git命令下载的就可以正常编译
