### ISSUE TITLE
--add-module=/path/to/nginx-gridfs/source/ outdated???

### ISSUE THREAD

**Issue by stevenkolstad** [mdirolf/nginx-gridfs#33]
Is it just me or does this path no longer exist? --add-module=/path/to/nginx-gridfs/source/ there is no source directory????

So what should I add to nginx?

Thanks,

Steve

**Comment by banker** [comment]
That's path is an example. Replace with the path to the nginx-gridfs source path.

**Comment by stevenkolstad** [comment]
Oh, whoops. I literally thought you meant ~/nginx-gridfs/source. Got it, Thanks!
