### ISSUE TITLE
Ignoring mimetypes

### ISSUE THREAD

**Issue by ghost** [mdirolf/nginx-gridfs#4]
It's marked as a todo in the code, so this is a known issue, but I'd like to get a vote in for content types other than text/plain...

**Comment by mdirolf** [comment]
yes, other than fixing the corruption issue you saw this is the first "feature" i want to add as well... it's on the top of the list

**Comment by jszmajda** [comment]
I have a very simple patch to push content-type determination back onto nginx. It appears that if you don't explicitely set the content-type, then ngx_http_core_module's ngx_http_set_content_type function will do it for you. Here's the patch:

diff --git a/ngx_http_gridfs_module.c b/ngx_http_gridfs_module.c
index d5ceb77..30fa6a8 100644
--- a/ngx_http_gridfs_module.c
+++ b/ngx_http_gridfs_module.c
@@ -209,8 +209,6 @@ static ngx_int_t ngx_http_gridfs_handler(ngx_http_request_t\* request) {

```
 request->headers_out.status = NGX_HTTP_OK;
 request->headers_out.content_length_n = gridfile.length;
```
-    request->headers_out.content_type.len = strlen(gridfile.mimetype);
-    request->headers_out.content_type.data = (u_char*) gridfile.mimetype;
   ngx_http_send_header(request);
  
   buffer = ngx_pcalloc(request->pool, sizeof(ngx_buf_t));

**Comment by mdirolf** [comment]
Josh - thanks! Do you mind forking and applying this patch and i'll merge back in? Just easier that way (especially since the github inbox mangles your patch as it is).

**Comment by jszmajda** [comment]
heh, it sure does. No problem: forked, committed, and pushed. I'm fairly new to github, you need anything else from me?

**Comment by mdirolf** [comment]
this is perfect. applied. i made a comment that we will eventually want to override Nginx's content-type w/ the one from GridFS (if there is one). but i think for now this is good. closing this issue.

**Comment by sho** [comment]
Sorry to be a constant fly in the ointment but this isn't actually working for me either on linux (RHEL5) or OSX, nginx version 0.8.30. The file goes through fine but the header is just not sent at all. Which is actually an improvement over text/plain, but still : )

Is there something I need to do in nginx config to turn on this functionality?
