### ISSUE TITLE
content type from GridFS should get used if it exists

### ISSUE THREAD

**Issue by mdirolf** [mdirolf/nginx-gridfs#5]
otherwise just don't set it and fall back to Nginx, as currently happens. see this patch:
http://github.com/stunti/nginx-gridfs/commit/15eebd1cf54aded8403d02f3e5a97fa578ecc55a

**Comment by ctriolo** [comment]
Working in the last [commit](http://github.com/mdirolf/nginx-gridfs/commit/81f2df92e0cfcfaacb626adbafa3c2d4ea50f749).
