### ISSUE TITLE
nginx-gridfs module build problem on Ubuntu 9.10

### ISSUE THREAD

**Issue by danoyoung** [mdirolf/nginx-gridfs#6]
Hello, I'm trying to build nginx-0.8.31 on Ubuntu 9.10 with the nginx-
gridfs module (from git clone git://github.com/mdirolf/nginx-gridfs.git
)

I've tried both

NO_WARNING_CHECKS=yes ./configure --add-module=/home/dyoung/src/nginx-
gridfs/
and
./configure --add-module=/home/dyoung/src/nginx-gridfs/

and I keep getting the same error during make. The configure runs
fine. I'm able to build and install nginx-0.8.31 no problem if I
don't add the nginx-gridfs module.

....
....
(.text+0x1c10): undefined reference to `pthread_join'
/usr/lib/libboost_thread-mt.a(once.o): In function
`boost::detail::get_once_per_thread_epoch()':
(.text+0x17): undefined reference to `pthread_once'
/usr/lib/libboost_thread-mt.a(once.o): In function
`boost::detail::get_once_per_thread_epoch()':
(.text+0x24): undefined reference to `pthread_getspecific'
/usr/lib/libboost_thread-mt.a(once.o): In function
`boost::detail::get_once_per_thread_epoch()':
(.text+0x53): undefined reference to `pthread_setspecific'
/usr/lib/libboost_thread-mt.a(once.o): In function
`create_epoch_tss_key':
(.text+0x86): undefined reference to `pthread_key_create'
collect2: ld returned 1 exit status
make[1]: *** [objs/nginx] Error 1
make[1]: Leaving directory`/home/dyoung/Downloads/nginx-0.8.31'
make: **\* [build] Error 2

I'm currently running mongodb-linux-i686-2010-01-04.

Any advice/insight would be greatly appreciated.

Regards,

Dan

**Comment by mdirolf** [comment]
hmm this looks like  a boost issue - not really sure what's going on here. i've got a halfway done branch of this project that will remove the boost dependency. just a matter of finding some time to finish it up and push it. hopefully within the next couple of weeks...

**Comment by jszmajda** [comment]
Dan: do you have all of build-essential installed? It looks like it can't find something from a pthread header.. Which libboost do you have installed? (dpkg -l |grep libboost)

**Comment by mdirolf** [comment]
can you try again now? dependency on boost has been removed in favor of using the mongo-c-driver
