### ISSUE TITLE
support for _id

### ISSUE THREAD

**Issue by ashokrkm** [mdirolf/nginx-gridfs#9]
it will be great to have support for _id.
filename is completely optional in GridFS and another thing to be maintained if we want to use nginx-gridfs.

**Comment by mdirolf** [comment]
agreed. unfortunately i don't have too much time to maintain this project so a patch / pull-request would be greatly appreciated. otherwise i'll try to get to this as soon as i can

**Comment by ashokrkm** [comment]
i think just the support _id will make it fully feature complete! sorry, i dont have any c or c++ or nginx programming experience :(

**Comment by mdirolf** [comment]
this has been added w/ chris' recent commits - check it out!
